In [1]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00422/wifi_localization.txt

--2021-08-11 00:21:07--  https://archive.ics.uci.edu/ml/machine-learning-databases/00422/wifi_localization.txt
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62000 (61K) [application/x-httpd-php]
Saving to: ‘wifi_localization.txt’

wifi_localization.t 100%[===================>]  60.55K  --.-KB/s    in 0.1s    

2021-08-11 00:21:07 (467 KB/s) - ‘wifi_localization.txt’ saved [62000/62000]



In [2]:
!ls

sample_data  wifi_localization.txt


In [3]:
!head wifi_localization.txt

-64	-56	-61	-66	-71	-82	-81	1
-68	-57	-61	-65	-71	-85	-85	1
-63	-60	-60	-67	-76	-85	-84	1
-61	-60	-68	-62	-77	-90	-80	1
-63	-65	-60	-63	-77	-81	-87	1
-64	-55	-63	-66	-76	-88	-83	1
-65	-61	-65	-67	-69	-87	-84	1
-61	-63	-58	-66	-74	-87	-82	1
-65	-60	-59	-63	-76	-86	-82	1
-62	-60	-66	-68	-80	-86	-91	1


In [4]:
import pandas as pd
import numpy as np

In [5]:
data = np.loadtxt('wifi_localization.txt')

In [6]:
data

array([[-64., -56., -61., ..., -82., -81.,   1.],
       [-68., -57., -61., ..., -85., -85.,   1.],
       [-63., -60., -60., ..., -85., -84.,   1.],
       ...,
       [-62., -59., -46., ..., -87., -88.,   4.],
       [-62., -58., -52., ..., -90., -85.,   4.],
       [-59., -50., -45., ..., -88., -87.,   4.]])

In [7]:
cols_wifi_nomes = [f'wifi_{i+1}' for i in range(7)]
cols_wifi_nomes

['wifi_1', 'wifi_2', 'wifi_3', 'wifi_4', 'wifi_5', 'wifi_6', 'wifi_7']

In [9]:
data_df = pd.DataFrame(data, columns= cols_wifi_nomes+['sala'])

In [10]:
data_df

wifi_1  wifi_2  wifi_3  wifi_4  wifi_5  wifi_6  wifi_7  sala
0      -64.0   -56.0   -61.0   -66.0   -71.0   -82.0   -81.0   1.0
1      -68.0   -57.0   -61.0   -65.0   -71.0   -85.0   -85.0   1.0
2      -63.0   -60.0   -60.0   -67.0   -76.0   -85.0   -84.0   1.0
3      -61.0   -60.0   -68.0   -62.0   -77.0   -90.0   -80.0   1.0
4      -63.0   -65.0   -60.0   -63.0   -77.0   -81.0   -87.0   1.0
...      ...     ...     ...     ...     ...     ...     ...   ...
1995   -59.0   -59.0   -48.0   -66.0   -50.0   -86.0   -94.0   4.0
1996   -59.0   -56.0   -50.0   -62.0   -47.0   -87.0   -90.0   4.0
1997   -62.0   -59.0   -46.0   -65.0   -45.0   -87.0   -88.0   4.0
1998   -62.0   -58.0   -52.0   -61.0   -41.0   -90.0   -85.0   4.0
1999   -59.0   -50.0   -45.0   -60.0   -45.0   -88.0   -87.0   4.0

[2000 rows x 8 columns]

In [11]:
data_df['sala'] = data_df['sala'].astype('object')

In [12]:
data_df.dtypes

wifi_1    float64
wifi_2    float64
wifi_3    float64
wifi_4    float64
wifi_5    float64
wifi_6    float64
wifi_7    float64
sala       object
dtype: object

In [13]:
data_df

wifi_1  wifi_2  wifi_3  wifi_4  wifi_5  wifi_6  wifi_7 sala
0      -64.0   -56.0   -61.0   -66.0   -71.0   -82.0   -81.0    1
1      -68.0   -57.0   -61.0   -65.0   -71.0   -85.0   -85.0    1
2      -63.0   -60.0   -60.0   -67.0   -76.0   -85.0   -84.0    1
3      -61.0   -60.0   -68.0   -62.0   -77.0   -90.0   -80.0    1
4      -63.0   -65.0   -60.0   -63.0   -77.0   -81.0   -87.0    1
...      ...     ...     ...     ...     ...     ...     ...  ...
1995   -59.0   -59.0   -48.0   -66.0   -50.0   -86.0   -94.0    4
1996   -59.0   -56.0   -50.0   -62.0   -47.0   -87.0   -90.0    4
1997   -62.0   -59.0   -46.0   -65.0   -45.0   -87.0   -88.0    4
1998   -62.0   -58.0   -52.0   -61.0   -41.0   -90.0   -85.0    4
1999   -59.0   -50.0   -45.0   -60.0   -45.0   -88.0   -87.0    4

[2000 rows x 8 columns]

In [14]:
data_df.describe()

wifi_1       wifi_2  ...       wifi_6       wifi_7
count  2000.000000  2000.000000  ...  2000.000000  2000.000000
mean    -52.330500   -55.623500  ...   -80.985000   -81.726500
std      11.321677     3.417688  ...     6.516672     6.519812
min     -74.000000   -74.000000  ...   -97.000000   -98.000000
25%     -61.000000   -58.000000  ...   -86.000000   -87.000000
50%     -55.000000   -56.000000  ...   -82.000000   -83.000000
75%     -46.000000   -53.000000  ...   -77.000000   -78.000000
max     -10.000000   -45.000000  ...   -61.000000   -63.000000

[8 rows x 7 columns]

In [15]:
data_df.sala.value_counts()

4.0    500
3.0    500
2.0    500
1.0    500
Name: sala, dtype: int64

In [16]:
X = data[:,:-1]
print(X.shape)
print(X)

(2000, 7)
[[-64. -56. -61. ... -71. -82. -81.]
 [-68. -57. -61. ... -71. -85. -85.]
 [-63. -60. -60. ... -76. -85. -84.]
 ...
 [-62. -59. -46. ... -45. -87. -88.]
 [-62. -58. -52. ... -41. -90. -85.]
 [-59. -50. -45. ... -45. -88. -87.]]


In [17]:
y = data[:,-1]
y = y.astype('int8')
print(y.shape)
print(y.dtype)
print(y)


(2000,)
int8
[1 1 1 ... 4 4 4]


In [66]:
from sklearn.model_selection import train_test_split

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=27)

In [68]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1600, 7)
(400, 7)
(1600,)
(400,)


In [69]:
pd.DataFrame(X_train, columns= cols_wifi_nomes).describe()

wifi_1       wifi_2  ...       wifi_6       wifi_7
count  1600.000000  1600.000000  ...  1600.000000  1600.000000
mean    -52.087500   -55.640625  ...   -80.982500   -81.711875
std      11.335294     3.444218  ...     6.550211     6.583859
min     -73.000000   -74.000000  ...   -97.000000   -98.000000
25%     -61.000000   -58.000000  ...   -86.000000   -87.000000
50%     -53.000000   -56.000000  ...   -82.000000   -83.000000
75%     -45.750000   -53.000000  ...   -77.000000   -78.000000
max     -10.000000   -45.000000  ...   -62.000000   -63.000000

[8 rows x 7 columns]

In [70]:
pd.DataFrame(y_test, columns=['y'])['y'].value_counts()

1    128
2     92
4     91
3     89
Name: y, dtype: int64

In [71]:
from sklearn.preprocessing import MinMaxScaler

In [72]:
X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)

In [73]:
pd.DataFrame(X_train, columns= cols_wifi_nomes).describe()

wifi_1       wifi_2  ...       wifi_6       wifi_7
count  1600.000000  1600.000000  ...  1600.000000  1600.000000
mean      0.331944     0.633082  ...     0.457643     0.465375
std       0.179925     0.118766  ...     0.187149     0.188110
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.190476     0.551724  ...     0.314286     0.314286
50%       0.317460     0.620690  ...     0.428571     0.428571
75%       0.432540     0.724138  ...     0.571429     0.571429
max       1.000000     1.000000  ...     1.000000     1.000000

[8 rows x 7 columns]

In [64]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical

In [74]:
y_train

array([1, 2, 2, ..., 4, 4, 3], dtype=int8)

In [75]:
y_train.shape

(1600,)

In [76]:
to_categorical(y_train)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [77]:
to_categorical(y_train)[:,0].sum()

0.0

In [78]:
to_categorical(y_train)[:,1:]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)

In [79]:
y_train = to_categorical(y_train)[:,1:]
y_test = to_categorical(y_test)[:,1:]

In [80]:
print(y_train.shape)
print(y_test.shape)

(1600, 4)
(400, 4)


In [81]:
from tensorflow import keras
from tensorflow.keras import layers

In [82]:
model = keras.Sequential(name = "PrimeiraMLP")
model.add(keras.Input(shape=(7,)))
model.add(layers.Dense(10, activation = "sigmoid"))
model.add(layers.Dense(4, activation= "softmax"))


In [83]:
model.layers

In [84]:
model.layers[0].weights

[<tf.Variable 'dense_2/kernel:0' shape=(7, 10) dtype=float32, numpy=
 array([[-0.0477888 ,  0.40189743, -0.04536164, -0.53507525, -0.25366268,
         -0.37898415,  0.23621339,  0.10588896,  0.56349623,  0.08190531],
        [ 0.5590185 ,  0.23171681, -0.5783816 ,  0.27121478, -0.39861697,
         -0.3322672 ,  0.46141005, -0.5781517 , -0.29224178, -0.08385742],
        [ 0.3149699 , -0.13487184, -0.37783262, -0.5033398 , -0.46192163,
          0.01311022, -0.35239816, -0.18717602, -0.45204866,  0.2511974 ],
        [-0.26039815,  0.3669231 , -0.10771984,  0.02246821, -0.35403582,
         -0.11393237, -0.43593195,  0.37421   , -0.3392531 ,  0.1743406 ],
        [-0.58700305, -0.49824524,  0.18115836, -0.30245045, -0.21456176,
         -0.31737354,  0.17284727, -0.30777773, -0.10100177,  0.14178663],
        [-0.4825077 , -0.43196356,  0.07420582, -0.43861222,  0.35384405,
          0.44821692,  0.1468479 , -0.275917  , -0.57078254,  0.45739603],
        [ 0.26314646, -0.01118094, -0

In [85]:
model.summary()

Model: "PrimeiraMLP"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 10)                80        
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 44        
Total params: 124
Trainable params: 124
Non-trainable params: 0
_________________________________________________________________


In [86]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [87]:
model.fit(X_train, y_train, epochs=20, batch_size=8)

Epoch 1/20
200/200 [==============================] - 1s 1ms/step - loss: 1.4131 - accuracy: 0.2556
Epoch 2/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3866 - accuracy: 0.2581
Epoch 3/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3789 - accuracy: 0.2781
Epoch 4/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3730 - accuracy: 0.2206
Epoch 5/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3666 - accuracy: 0.3762
Epoch 6/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3604 - accuracy: 0.3875
Epoch 7/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3536 - accuracy: 0.4100
Epoch 8/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3464 - accuracy: 0.4837
Epoch 9/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3391 - accuracy: 0.4988
Epoch 10/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3308 - accuracy: 0.5644

In [88]:
_, accuracy = model.evaluate(X_test, y_test, batch_size=32)
print('Accuracy: %.2f' % (accuracy*100))


13/13 [==============================] - 0s 1ms/step - loss: 1.2040 - accuracy: 0.7550
Accuracy: 75.50


In [89]:
model.layers[0].weights

[<tf.Variable 'dense_2/kernel:0' shape=(7, 10) dtype=float32, numpy=
 array([[-0.42193645,  0.10383124, -0.3687321 , -0.7874641 , -0.3466941 ,
         -0.19543673,  0.7042785 ,  0.34805518,  0.55992293,  0.0468915 ],
        [ 0.6056273 ,  0.19903892, -0.51338583,  0.38966635, -0.36535752,
         -0.36378735,  0.4420325 , -0.5421173 , -0.32391718, -0.04996553],
        [ 0.55800587, -0.44407612, -0.53793854, -0.50558037, -0.3111927 ,
          0.10073867, -0.34386647, -0.3072414 , -0.4436642 ,  0.39566222],
        [-0.61665845,  0.066586  , -0.42536807, -0.22115694, -0.43977383,
          0.06560288,  0.02113261,  0.6084959 , -0.34499088,  0.14618841],
        [-0.04000153, -0.77272946,  0.10944545, -0.19704348,  0.03999419,
         -0.13924652, -0.12460164, -0.7079301 ,  0.07775851,  0.25739408],
        [-0.9054111 , -0.5323636 , -0.06047218, -0.56219864,  0.21048735,
          0.5771254 ,  0.5080194 , -0.00142086, -0.5529609 ,  0.33556908],
        [-0.12293671, -0.13386282, -0